sudo: false
language: go
go:
  - 1.12.x
  - tip
env:
  - GO111MODULE=on
addons:
  apt:
    packages:
      - unzip
before_install:
  - go get -u github.com/gunk/gunk
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
install:
  - gunk generate -v -x ./...
  - go install -v .
script:
  - ls -Ral *swagger.json v1
