// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package gunk.example.v1;

public interface CheckStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gunk.example.v1.CheckStatusResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.gunk.example.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  int getStatusValue();
  /**
   * <code>.gunk.example.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  gunk.example.v1.Status getStatus();

  /**
   * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Deprecated int getOldField();
}
