// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package gunk.example.v1;

public interface CountryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gunk.example.v1.Country)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string Name = 1[json_name = "name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1[json_name = "name", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCode();
  /**
   * <code>string Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
