// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package gunk.example.v1;

public interface GetCountriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gunk.example.v1.GetCountriesRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.util.List<java.lang.String>
      getCountriesList();
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  int getCountriesCount();
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getCountries(int index);
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getCountriesBytes(int index);
}
