// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package example.api.v1;

/**
 * <pre>
 * CheckStatusResponse is the server health status response.
 * </pre>
 *
 * Protobuf type {@code v1.CheckStatusResponse}
 */
public  final class CheckStatusResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CheckStatusResponse, CheckStatusResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:v1.CheckStatusResponse)
    CheckStatusResponseOrBuilder {
  private CheckStatusResponse() {
  }
  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public example.api.v1.Status getStatus() {
    example.api.v1.Status result = example.api.v1.Status.forNumber(status_);
    return result == null ? example.api.v1.Status.UNRECOGNIZED : result;
  }
  /**
   * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setStatus(example.api.v1.Status value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    status_ = value.getNumber();
  }
  /**
   * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearStatus() {
    
    status_ = 0;
  }

  public static final int OLDFIELD_FIELD_NUMBER = 2;
  private int oldField_;
  /**
   * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  @java.lang.Deprecated public int getOldField() {
    return oldField_;
  }
  /**
   * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setOldField(int value) {
    
    oldField_ = value;
  }
  /**
   * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearOldField() {
    
    oldField_ = 0;
  }

  public static example.api.v1.CheckStatusResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.CheckStatusResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.CheckStatusResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.CheckStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(example.api.v1.CheckStatusResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * CheckStatusResponse is the server health status response.
   * </pre>
   *
   * Protobuf type {@code v1.CheckStatusResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        example.api.v1.CheckStatusResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:v1.CheckStatusResponse)
      example.api.v1.CheckStatusResponseOrBuilder {
    // Construct using example.api.v1.CheckStatusResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public example.api.v1.Status getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setStatus(example.api.v1.Status value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.v1.Status Status = 1[json_name = "status", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    @java.lang.Deprecated public int getOldField() {
      return instance.getOldField();
    }
    /**
     * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Deprecated public Builder setOldField(int value) {
      copyOnWrite();
      instance.setOldField(value);
      return this;
    }
    /**
     * <code>int32 OldField = 2[json_name = "old_field", ctype = STRING, deprecated = true, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Deprecated public Builder clearOldField() {
      copyOnWrite();
      instance.clearOldField();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:v1.CheckStatusResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new example.api.v1.CheckStatusResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "status_",
            "oldField_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<example.api.v1.CheckStatusResponse> parser = PARSER;
        if (parser == null) {
          synchronized (example.api.v1.CheckStatusResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<example.api.v1.CheckStatusResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:v1.CheckStatusResponse)
  private static final example.api.v1.CheckStatusResponse DEFAULT_INSTANCE;
  static {
    CheckStatusResponse defaultInstance = new CheckStatusResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CheckStatusResponse.class, defaultInstance);
  }

  public static example.api.v1.CheckStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CheckStatusResponse> PARSER;

  public static com.google.protobuf.Parser<CheckStatusResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

