// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package example.api.v1;

/**
 * <pre>
 * GetCountriesRequest is the get countries request.
 * </pre>
 *
 * Protobuf type {@code v1.GetCountriesRequest}
 */
public  final class GetCountriesRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetCountriesRequest, GetCountriesRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:v1.GetCountriesRequest)
    GetCountriesRequestOrBuilder {
  private GetCountriesRequest() {
    countries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int COUNTRIES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> countries_;
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getCountriesList() {
    return countries_;
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getCountriesCount() {
    return countries_.size();
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getCountries(int index) {
    return countries_.get(index);
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountriesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        countries_.get(index));
  }
  private void ensureCountriesIsMutable() {
    if (!countries_.isModifiable()) {
      countries_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(countries_);
     }
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCountries(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureCountriesIsMutable();
    countries_.set(index, value);
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addCountries(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureCountriesIsMutable();
    countries_.add(value);
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addAllCountries(
      java.lang.Iterable<java.lang.String> values) {
    ensureCountriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, countries_);
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCountries() {
    countries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void addCountriesBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureCountriesIsMutable();
    countries_.add(value.toStringUtf8());
  }

  public static example.api.v1.GetCountriesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.GetCountriesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.GetCountriesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.GetCountriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(example.api.v1.GetCountriesRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * GetCountriesRequest is the get countries request.
   * </pre>
   *
   * Protobuf type {@code v1.GetCountriesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        example.api.v1.GetCountriesRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:v1.GetCountriesRequest)
      example.api.v1.GetCountriesRequestOrBuilder {
    // Construct using example.api.v1.GetCountriesRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getCountriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getCountriesList());
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getCountriesCount() {
      return instance.getCountriesCount();
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getCountries(int index) {
      return instance.getCountries(index);
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountriesBytes(int index) {
      return instance.getCountriesBytes(index);
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCountries(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setCountries(index, value);
      return this;
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addCountries(
        java.lang.String value) {
      copyOnWrite();
      instance.addCountries(value);
      return this;
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addAllCountries(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllCountries(values);
      return this;
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCountries() {
      copyOnWrite();
      instance.clearCountries();
      return this;
    }
    /**
     * <code>repeated string Countries = 1[json_name = "countries", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder addCountriesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addCountriesBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:v1.GetCountriesRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new example.api.v1.GetCountriesRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "countries_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<example.api.v1.GetCountriesRequest> parser = PARSER;
        if (parser == null) {
          synchronized (example.api.v1.GetCountriesRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<example.api.v1.GetCountriesRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:v1.GetCountriesRequest)
  private static final example.api.v1.GetCountriesRequest DEFAULT_INSTANCE;
  static {
    GetCountriesRequest defaultInstance = new GetCountriesRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetCountriesRequest.class, defaultInstance);
  }

  public static example.api.v1.GetCountriesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetCountriesRequest> PARSER;

  public static com.google.protobuf.Parser<GetCountriesRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

