// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package example.api.v1;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:v1.Message)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  java.lang.String getMsg();
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  int getCode();
}
