// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: all.proto

package example.api.v1;

/**
 * <pre>
 * Message is a echo message.
 * </pre>
 *
 * Protobuf type {@code v1.Message}
 */
public  final class Message extends
    com.google.protobuf.GeneratedMessageLite<
        Message, Message.Builder> implements
    // @@protoc_insertion_point(message_implements:v1.Message)
    MessageOrBuilder {
  private Message() {
    msg_ = "";
  }
  public static final int MSG_FIELD_NUMBER = 1;
  private java.lang.String msg_;
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public java.lang.String getMsg() {
    return msg_;
  }
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(msg_);
  }
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMsg(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    msg_ = value;
  }
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearMsg() {
    
    msg_ = getDefaultInstance().getMsg();
  }
  /**
   * <pre>
   * Msg holds a message.
   * </pre>
   *
   * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setMsgBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    msg_ = value.toStringUtf8();
  }

  public static final int CODE_FIELD_NUMBER = 2;
  private int code_;
  /**
   * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }
  /**
   * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void setCode(int value) {
    
    code_ = value;
  }
  /**
   * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
   */
  private void clearCode() {
    
    code_ = 0;
  }

  public static example.api.v1.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static example.api.v1.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static example.api.v1.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static example.api.v1.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static example.api.v1.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(example.api.v1.Message prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Message is a echo message.
   * </pre>
   *
   * Protobuf type {@code v1.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        example.api.v1.Message, Builder> implements
      // @@protoc_insertion_point(builder_implements:v1.Message)
      example.api.v1.MessageOrBuilder {
    // Construct using example.api.v1.Message.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Msg holds a message.
     * </pre>
     *
     * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      return instance.getMsg();
    }
    /**
     * <pre>
     * Msg holds a message.
     * </pre>
     *
     * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      return instance.getMsgBytes();
    }
    /**
     * <pre>
     * Msg holds a message.
     * </pre>
     *
     * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMsg(
        java.lang.String value) {
      copyOnWrite();
      instance.setMsg(value);
      return this;
    }
    /**
     * <pre>
     * Msg holds a message.
     * </pre>
     *
     * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearMsg() {
      copyOnWrite();
      instance.clearMsg();
      return this;
    }
    /**
     * <pre>
     * Msg holds a message.
     * </pre>
     *
     * <code>string Msg = 1[json_name = "msg", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setMsgBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMsgBytes(value);
      return this;
    }

    /**
     * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    @java.lang.Override
    public int getCode() {
      return instance.getCode();
    }
    /**
     * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder setCode(int value) {
      copyOnWrite();
      instance.setCode(value);
      return this;
    }
    /**
     * <code>int32 Code = 2[json_name = "code", ctype = STRING, deprecated = false, lazy = false, jstype = JS_NORMAL, weak = false];</code>
     */
    public Builder clearCode() {
      copyOnWrite();
      instance.clearCode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:v1.Message)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new example.api.v1.Message();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "msg_",
            "code_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<example.api.v1.Message> parser = PARSER;
        if (parser == null) {
          synchronized (example.api.v1.Message.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<example.api.v1.Message>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:v1.Message)
  private static final example.api.v1.Message DEFAULT_INSTANCE;
  static {
    Message defaultInstance = new Message();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Message.class, defaultInstance);
  }

  public static example.api.v1.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Message> PARSER;

  public static com.google.protobuf.Parser<Message> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

